'use client';

import * as React from 'react';
import QRCode from 'qrcode';

/**
 * A real, scannable QR code for the share link. Rendered as an inline SVG
 * generated by the `qrcode` encoder (library output only — the URL is encoded
 * into module geometry, never interpolated as markup). Always dark-on-white:
 * inverted QR codes fail on many phone scanners, so it ignores the dark theme.
 */
export function ShareQr({ value, label, size = 176 }: { value: string; label: string; size?: number }) {
  const [svg, setSvg] = React.useState<string | null>(null);

  React.useEffect(() => {
    let cancelled = false;
    QRCode.toString(value, {
      type: 'svg',
      errorCorrectionLevel: 'M',
      margin: 2,
      color: { dark: '#000000', light: '#ffffff' },
    })
      .then((out) => {
        if (!cancelled) setSvg(out);
      })
      .catch(() => {
        if (!cancelled) setSvg(null);
      });
    return () => {
      cancelled = true;
    };
  }, [value]);

  if (!svg) return null;
  return (
    <div
      role="img"
      aria-label={label}
      data-testid="share-qr"
      className="overflow-hidden rounded-md bg-white p-token-2 [&>svg]:h-full [&>svg]:w-full"
      style={{ width: size, height: size }}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
